version: '3.2'
services:

  api:
    build:
      context: .
    env_file:
      - .env_compose
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "11000:8081"
    depends_on:
      - pgsql

  pgsql:
    image: postgres:15-alpine
    restart: always
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
    ports:
      - 15435:5432
    environment:
      POSTGRES_PASSWORD: rec_task
      POSTGRES_USER: rec_task

  pgsql_test:
    image: postgres:15-alpine
    restart: always
    volumes:
      - type: bind
        source: /tmp
        target: /tmp
    ports:
      - 15436:5432
    environment:
      POSTGRES_PASSWORD: rec_task_test
      POSTGRES_USER: rec_task_test