"""add_team_hirerchy_self_refrencial_FK

Revision ID: 313ea711456b
Revises: d637d5c66926
Create Date: 2024-01-12 00:36:07.761531

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '313ea711456b'
down_revision = 'd637d5c66926'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('team', sa.Column('parent_team_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'team', 'team', ['parent_team_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("team_parent_team_id_fkey", 'team', type_='foreignkey')
    op.drop_column('team', 'parent_team_id')
    # ### end Alembic commands ###
