"""Fix_sample_ration_-_>_sample_ratio

Revision ID: eaad909233cf
Revises: dd33958b548b
Create Date: 2024-01-10 22:02:07.733530

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eaad909233cf'
down_revision = 'dd33958b548b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('sample_ratio', sa.Integer(), nullable=False))
    op.drop_column('experiment', 'sample_ration')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('experiment', sa.Column('sample_ration', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('experiment', 'sample_ratio')
    # ### end Alembic commands ###
